export const ALL_ROOM_SUCCESS = "ALL_ROOM_SUCCESS";
export const ALL_ROOM_FAIL = "ALL_ROOM_FAIL";

export const ROOMS_DETAILS_SUCCESS = "ROOMS_DETAILS_SUCCESS";
export const ROOMS_DETAILS_FAIL = "ROOMS_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";